#!/bin/bash

if [ -z "$1" ]; then
	echo "Error: No project name provided."
	echo "Usage: ./create-project.sh <project-name> [--venv]"
	exit 1
fi 

PROJECT_NAME=$1
CREATE_VENV=false

if [ "$2" == "--venv" ]; then
	CREATE_VENV=true
fi

echo "creatin project: $PROJECT_NAME"

mkdir -p $PROJECT_NAME/{src,tests,docs}

cat > $PROJECT_NAME/README.md <<EOF

# $PROJECT_NAME

Generated by the DevOps-automation-toolkit
EOF

cd $PROJECT_NAME
git init -q

if [ "$CREATE_VENV" = true ];then
	python3 -m venv venv
fi

git add .
git commit -m "Initial project setup" -q

echo "Done"
